---
name: Linting
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  validation:
    name: Validate package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

        with:
          persist-credentials: false

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: Azd325/arch-pkgbuild-builder@1df308b1218f91dd79a496b7dae1383b3bcb2d14
        with:
          target: "pkgbuild"
          builddir: "gitkraken-aur"
          pkgname: "gitkraken"

      - name: Validate SRCINFO
        id: validate-srcinfo
        uses: Azd325/arch-pkgbuild-builder@1df308b1218f91dd79a496b7dae1383b3bcb2d14
        with:
          target: "srcinfo"
          builddir: "gitkraken-aur"
          pkgname: "gitkraken"
  linter:
    name: Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@d5b0a2ab116623730dd094f15ddc1b6b25bf7b99
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_HTML: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
